In [3]:
# operasi penjumlahan vektor
# menggunakan list

a = [1,2,3]
b = [5,1,2]

def jumlah(a,b):
    c = [0] * len(a)
    for i in range(len(a)):
        c[i] = a[i] + b[i]
    return c


In [4]:
jumlah(a,b)

[6, 3, 5]

In [5]:
# tipe data dari numpy -> np.array
import numpy as np

a = [1,2,3,4]
b = [6,4,2,7]

np_a = np.array(a)
np_b = np.array(b)

In [6]:
np_a

array([1, 2, 3, 4])

In [7]:
np_a + np_b

array([ 7,  6,  5, 11])

In [11]:
# CEK PERFORMA
a = [1] * 1000
b = [2] * 1000


In [12]:
%timeit jumlah(a,b)

83.4 µs ± 3.94 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [13]:
np_a = np.array(a)
np_b = np.array(b)

%timeit np_a + np_b

1.42 µs ± 194 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [14]:
# contoh array
a2d = [[1,3], [5,4], [7,8]]
a2d = np.array(a2d)
a2d

array([[1, 3],
       [5, 4],
       [7, 8]])

In [23]:
a = [1,2,3,4,5,'f']
a = np.array(a)
a

array(['1', '2', '3', '4', '5', 'f'], dtype='<U11')

In [24]:
A = [[1,3], [5,4], [7,8]]
A = np.array(A)
A

array([[1, 3],
       [5, 4],
       [7, 8]])

In [29]:
# memanggil angka tertentu
A[2][0]


7

In [30]:
A[2,1]

8

In [31]:
# memanggil baris
A[1,:]

array([5, 4])

In [32]:
A[1]

array([5, 4])

In [33]:
# memanggil kolom
A[:,0]

array([1, 5, 7])

In [37]:
# special array
np.zeros((5,1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [40]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [41]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [43]:
np.arange(1,4,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5])

In [47]:
np.linspace(1,5,15)

array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
       2.42857143, 2.71428571, 3.        , 3.28571429, 3.57142857,
       3.85714286, 4.14285714, 4.42857143, 4.71428571, 5.        ])

In [48]:
np.ones(3)

array([1., 1., 1.])

In [55]:
np.empty(4)

array([9.48277340e-312, 4.67296746e-307, 1.69121096e-306, 3.33772792e-307])

In [56]:
type(np.array([1,2,3]))

numpy.ndarray

In [57]:
A = [[1,3], [5,4], [7,8]]
A = np.array(A)
A

array([[1, 3],
       [5, 4],
       [7, 8]])

In [58]:
A.ndim

2

In [59]:
A.shape

(3, 2)

In [60]:
A.size

6

In [61]:
a = [2,3,1,6,5,7,5,6]
a = np.array(a)
a

array([2, 3, 1, 6, 5, 7, 5, 6])

In [66]:
a.reshape((4,2))

array([[2, 3],
       [1, 6],
       [5, 7],
       [5, 6]])

In [67]:
a.reshape((4,2)).T

array([[2, 1, 5, 5],
       [3, 6, 7, 6]])

In [68]:
a = [2,3,1,6,5,7,5,6]
a = np.array(a)
a

array([2, 3, 1, 6, 5, 7, 5, 6])

In [74]:
a[:,np.newaxis]

array([[2],
       [3],
       [1],
       [6],
       [5],
       [7],
       [5],
       [6]])

In [75]:
a

array([2, 3, 1, 6, 5, 7, 5, 6])

In [83]:
np.expand_dims(a, axis=1).shape

(8, 1)

Querying

In [86]:
mat = [[5,4,3,8,2], [4,6,3,7,4], [1,6,4,5,6]]
mat = np.array(mat)
mat

array([[5, 4, 3, 8, 2],
       [4, 6, 3, 7, 4],
       [1, 6, 4, 5, 6]])

In [87]:
mat[:,2]

array([3, 3, 4])

In [90]:
mat[1:,2:]

array([[3, 7, 4],
       [4, 5, 6]])

In [91]:
mat[1:2, -2:]

array([[7, 4]])

In [92]:
mat

array([[5, 4, 3, 8, 2],
       [4, 6, 3, 7, 4],
       [1, 6, 4, 5, 6]])

In [95]:
mat[2:3, 1:]

array([[6, 4, 5, 6]])

In [96]:
mat > 4

array([[ True, False, False,  True, False],
       [False,  True, False,  True, False],
       [False,  True, False,  True,  True]])

In [97]:
mat[mat > 5]

array([8, 6, 7, 6, 6])

In [98]:
mahasiswa = np.array(['afif','felis','zahra','sayyid'])
nilai = np.array([70,80,90,85])

In [100]:
nilai < 60

array([False, False, False, False])

In [102]:
nilai[nilai < 60]

array([], dtype=int32)

In [103]:
mahasiswa[nilai == 80]

array(['felis'], dtype='<U6')

In [11]:
A = np.array([[1,2],[3,4]])
B = np.array([[6,5],[1,2]])
C = np.array([1,2])

In [12]:
A+B

array([[7, 7],
       [4, 6]])

In [13]:
A*B

array([[ 6, 10],
       [ 3,  8]])

In [14]:
A*C

array([[1, 4],
       [3, 8]])

In [15]:
# perkalian matriks secara aljabar linear
A @ B

array([[ 8,  9],
       [22, 23]])

In [16]:
A

array([[1, 2],
       [3, 4]])

In [17]:
A.mean(axis=0)

array([2., 3.])

In [118]:
np.random.random([2,3])

array([[0.29779969, 0.26940103, 0.87713245],
       [0.6481985 , 0.77061103, 0.29126867]])

In [8]:
import numpy as np
C = np.arange(0,12)
C = C.reshape((4,3))

In [9]:
C

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])