## 5 step implementasi Machine Learning

- Import library yang dibutuhkan
- Siapkan datanya (70 - 80%) effort
    - Data Cleansing
    - EDA
    - Feature Engineering / Extraction
- Siapkan algoritma machine learning
- Training machine learning
- Gunakan algoritma machine learning
    - Evaluasi
    - Prediksi

In [18]:
# step 1 : import library
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [5]:
# step 2 : siapkan dataset -> menjadikan data sebagai matriks
iris = load_iris()
X = iris.data
y = iris.target

print(f'Ukuran matriks X : {X.shape}')
print(f'Ukuran label : {y.shape}')

Ukuran matriks X : (150, 4)
Ukuran label : (150,)


In [6]:
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [7]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [12]:
# split data

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=46)

In [10]:
# pengertian untuk random_state
import numpy as np

np.random.seed(2)
np.random.random(10)

array([0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ,
       0.33033482, 0.20464863, 0.61927097, 0.29965467, 0.26682728])

In [8]:
# step 3 : Siapkan algoritma ML

model = KNeighborsClassifier()

In [13]:
# step 4 : training model
model.fit(X_train, y_train)

KNeighborsClassifier()

In [17]:
# step 5 : gunakan model
data_baru = [[2.5, 1.1, 5.4, 3.3],
             [3.5, 2.4, 2.1, 5.6]]
model.predict(data_baru)

array([2, 1])

In [19]:
# test / uji
y_pred = model.predict(X_test)

# evaluasi dengan akurasi
accuracy_score(y_test, y_pred)

0.9333333333333333